import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {familyReferenceField, planModelFamilyReference, applyModelFamilyReference} from '../scripts/migrations/0030-model-family-reference.mjs';
function fixture(){
 const models={slug:'models',fields:[{slug:'title',type:'string'}]};const families={slug:'families',fields:[{slug:'models',type:'reference',validation:{relation:'family_models',relationSide:'parent',targetCollection:'models'}}]};const writes=[];
 const api=async(path,options={})=>{if(options.method==='POST'){assert.equal(path,'/_emdash/api/schema/collections/models/fields');writes.push(structuredClone(options));models.fields.push(structuredClone(options.data));return{};}return{item:structuredClone(path.includes('/models?')?models:families)};};return{models,families,writes,api};
}
test('adds one inverse schema field after backup, without entry, relation or publication writes',async()=>{const f=fixture();const plan=await planModelFamilyReference(f.api);assert(plan.createField);await assert.rejects(applyModelFamilyReference(f.api,plan),/backup writer/);let backup=false;await applyModelFamilyReference(f.api,plan,{beforeWrite:()=>{assert.equal(f.writes.length,0);backup=true;}});assert(backup);assert.deepEqual(f.writes,[{method:'POST',data:familyReferenceField}]);assert.equal((await planModelFamilyReference(f.api)).createField,false);await applyModelFamilyReference(f.api,await planModelFamilyReference(f.api),{beforeWrite:()=>{throw Error('No-op should not back up');}});assert.equal(f.writes.length,1);});
test('refuses incompatible or duplicate inverse bindings',async()=>{for(const field of [{slug:'families',type:'string'},{...familyReferenceField,validation:{...familyReferenceField.validation,relationSide:'parent'}},{...familyReferenceField,slug:'other_families'}]){const f=fixture();f.models.fields.push(field);await assert.rejects(planModelFamilyReference(f.api));assert.equal(f.writes.length,0);}});
test('refuses concurrent model or family schema changes before creation',async()=>{for(const collection of ['models','families']){const f=fixture();const plan=await planModelFamilyReference(f.api);f[collection].fields.push({slug:'editor-change',type:'text'});await assert.rejects(applyModelFamilyReference(f.api,plan,{beforeWrite:()=>{}}),/changed since planning/);assert.equal(f.writes.length,0);}});
test('fresh installations and migration expose the identical native inverse binding',async()=>{const seed=JSON.parse(await readFile(new URL('../seed/seed.json',import.meta.url),'utf8'));assert.deepEqual(seed.collections.find(c=>c.slug==='models').fields.find(f=>f.slug==='families'),familyReferenceField);});
test('pins the bare target origin and strictly limits migration methods and paths',async()=>{const{validateOrigin,guardedMigrationApi}=await import('../scripts/migrations/0030-model-family-reference.mjs');for(const value of ['https://other.example/','https://user@cattelan-maroc-preview.cattelan.workers.dev/','https://cattelan-maroc-preview.cattelan.workers.dev/path','https://cattelan-maroc-preview.cattelan.workers.dev/?x=1'])assert.throws(()=>validateOrigin(value));assert.equal(validateOrigin('http://localhost:4331').origin,'http://localhost:4331');let calls=0;const api=guardedMigrationApi(()=>{calls++;});assert.throws(()=>api('/_emdash/api/schema/collections/models/fields',{method:'DELETE'}));assert.throws(()=>api('/_emdash/api/content/models'));assert.throws(()=>api('/_emdash/api/schema/collections/models/fields',{method:'POST',data:{slug:'wrong'}}));assert.equal(calls,0);});
